### ISSUE TITLE
"An item with the same key has already been added" when using inline partial to pass data to partial

### ISSUE THREAD

**Issue by johnknoop** [Handlebars-Net/Handlebars.Net#306]
I'm trying to render this template:

```hbs
{{#>my-layout}}
{{#*inline "title"}}My title{{/inline}}
	Some page content
{{/my-layout}}
```
This is the content of `my-layout`:
```hbs
<html>
<head>
	<title>{{>title}}</title>
</head>
<body>
	{{>@partial-block}}
</body>
</html>
```

Exception:
> Runtime error while rendering partial 'my-layout', see inner exception for more information

Inner exception:
>An item with the same key has already been added. Key: title

Stack trace:
```
   at HandlebarsDotNet.Compiler.PartialBinder.InvokePartial(String partialName, BindingContext context, HandlebarsConfiguration configuration)
   at HandlebarsDotNet.Compiler.PartialBinder.InvokePartialWithFallback(String partialName, BindingContext context, HandlebarsConfiguration configuration)
   at HandlebarsDotNet.Handlebars.HandlebarsEnvironment.<>c__DisplayClass7_0.<Compile>b__0(Object context)
```

Any ideas?

**Comment by johnknoop** [comment]
Update:

It renders if I change the template into this:

```hbs
{{#*inline "title"}}My title{{/inline}}
{{#>my-layout}}
	Some page content
{{/my-layout}}
```

But it's not actually the same thing, since [each inline partial is available to the current block and all children, including execution of other partials](https://handlebarsjs.com/partials.html#inline-partials) so the `title` partial now becomes available to the whole template, which is good enough for me right now, but not great in general.
