### ISSUE TITLE
Space(s) between "{{#>" and partial name when using partial block throws a HandlebarsCompilerException exception

### ISSUE THREAD

**Issue by cw-andrews** [Handlebars-Net/Handlebars.Net#392]
### Space(s) in opening of partial block usage throws `HandlebarsCompilerException`
This is best explained via an example.

This compiles:
```
{{#!>layout}}
something...
{{/layout}}
```
This doesn't:
```
{{#!> layout}}
something...
{{/layout}}
```
### Expected behavior:
`{{#> layout}}` should compile.

### Test(s) to reproduce
```csharp
    public class PartialBlockUsageCompilationTests
    {
        [Fact]
        public void NoSpaces_Compiles()
        {
            IHandlebars handlebars = Handlebars.Create();
            handlebars.RegisterTemplate("layout", "<opening>{{> @partial-block}}</closing>");
            
            Func<object, string> template = handlebars.Compile("{{#>layout}} {{@key}} {{/ layout}}");
            
            Assert.IsType<Func<object, string>>(template);
        }

        [Fact]
        public void IncludesSpaces_ThrowsHandlebarsCompilerException()
        {
            IHandlebars handlebars = Handlebars.Create();
            handlebars.RegisterTemplate("layout", "<opening>{{> @partial-block}}</closing>");
            
            Assert.Throws<HandlebarsCompilerException>(() => handlebars.Compile("{{#> layout}} {{@key}} {{/ layout}}"));
        }
    }
```

### Other related info

HandlebarsDotNet.HandlebarsCompilerException
  HResult=0x80131500
  Message=Reached end of template before block expression '' was closed
  Source=Handlebars
  StackTrace:
   at HandlebarsDotNet.Compiler.BlockAccumulator.AccumulateBlock(IEnumerator`1 enumerator, BlockAccumulatorContext context) in D:\a\Handlebars.Net\Handlebars.Net\source\Handlebars\Compiler\Lexer\Converter\BlockAccumulator.cs:line 56
   at HandlebarsDotNet.Compiler.BlockAccumulator.<ConvertTokens>d__3.MoveNext() in D:\a\Handlebars.Net\Handlebars.Net\source\Handlebars\Compiler\Lexer\Converter\BlockAccumulator.cs:line 33
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) in /_/src/System.Private.CoreLib/shared/System/Collections/Generic/List.cs:line 86
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) in /_/src/System.Linq/src/System/Linq/ToCollection.cs:line 30
   at HandlebarsDotNet.Compiler.BlockAccumulator.Accumulate(IEnumerable`1 tokens, HandlebarsConfiguration configuration) in D:\a\Handlebars.Net\Handlebars.Net\source\Handlebars\Compiler\Lexer\Converter\BlockAccumulator.cs:line 14
   at HandlebarsDotNet.Compiler.ExpressionBuilder.ConvertTokensToExpressions(IEnumerable`1 tokens) in D:\a\Handlebars.Net\Handlebars.Net\source\Handlebars\Compiler\ExpressionBuilder.cs:line 31
   at HandlebarsDotNet.Compiler.HandlebarsCompiler.Compile(TextReader source) in D:\a\Handlebars.Net\Handlebars.Net\source\Handlebars\Compiler\HandlebarsCompiler.cs:line 30
   at HandlebarsDotNet.Handlebars.HandlebarsEnvironment.Compile(TextReader template) in D:\a\Handlebars.Net\Handlebars.Net\source\Handlebars\HandlebarsEnvironment.cs:line 51
   at HandlebarsDotNet.Handlebars.HandlebarsEnvironment.Compile(String template) in D:\a\Handlebars.Net\Handlebars.Net\source\Handlebars\HandlebarsEnvironment.cs:line 58
   at HandlebarsDotNetTB.TemplateProvider.GetTemplatedString(String templateName) in C:\code\HandlebarsDotNetTB\HandlebarsDotNetTB\TemplateProvider.cs:line 34
   at HandlebarsDotNetTB.Program.Main(String[] args) in C:\code\HandlebarsDotNetTB\HandlebarsDotNetTB\Program.cs:line 11

**Comment by zjklee** [comment]
Hello @cw-andrews
Looks like a duplicate of https://github.com/Handlebars-Net/Handlebars.Net/issues/217 which is already fixed.

**Comment by cw-andrews** [comment]
@zjklee. Thanks. It looks like their hasn't been a release since your work was merged into master. Do you have any idea when the next release will be?

**Comment by zjklee** [comment]
@cw-andrews 
There are a couple of pre-release versions published.
As for the next release version I expect it to be published by the end of the week.

**Comment by cw-andrews** [comment]
@zjklee, Awesome, thanks.
