### ISSUE TITLE
Comments starting with HTML are parsed as layout tokens

### ISSUE THREAD

**Issue by heemskerkerik** [Handlebars-Net/Handlebars.Net#437]
### Describe the bug
When a comment in the template contains HTML, it is parsed as a `LayoutToken`. This in turn causes an `InvalidOperationException` when trying to render a view, because `HandlebarsCompiler.CompileView` expects there to only be a single `LayoutToken`.

An example of such a comment:
```hbs
{{!--
  <div>Something</div>
--}}
```

### Expected behavior:
The expected behavior is that the comment is treated as a `CommentToken`, and that compiling the view does not result in an `InvalidOperationException`.

### Test to reproduce
(In ViewEngineTests.cs)
```csharp
[Fact]
public void CanIgnoreCommentsContainingHtml()
{
    var files = new FakeFileSystem
                {
                    { "views\\layout.hbs", "Start\r\n{{{body}}}\r\nEnd" },
                    { "views\\someview.hbs", "{{!< layout}}\r\n\r\nTemplate\r\n{{!--\r\n<div>Commented out HTML</div>\r\n--}}" },
                };

    var handlebarsConfiguration = new HandlebarsConfiguration { FileSystem = files };
    var handlebars = Handlebars.Create(handlebarsConfiguration);
    var render = handlebars.CompileView("views\\someview.hbs");
    var output = render(null);

    Assert.Equal("Start\r\n\r\nTemplate\r\n\r\nEnd", output);
}
```

This currently fails:
```
System.InvalidOperationException
Sequence contains more than one element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at HandlebarsDotNet.Compiler.HandlebarsCompiler.CompileView(ViewReaderFactory readerFactoryFactory, String templatePath, CompilationContext compilationContext) in Handlebars.Net/source/Handlebars/Compiler/HandlebarsCompiler.cs:line 46
   at HandlebarsDotNet.HandlebarsEnvironment.CompileViewInternal(String templatePath, ViewReaderFactory readerFactoryFactory) in Handlebars.Net/source/Handlebars/HandlebarsEnvironment.cs:line 86
   at HandlebarsDotNet.HandlebarsEnvironment.CompileView(String templatePath) in Handlebars.Net/source/Handlebars/HandlebarsEnvironment.cs:line 52
   at HandlebarsDotNet.Test.ViewEngine.ViewEngineTests.CanIgnoreCommentsContainingHtml() in Handlebars.Net/source/Handlebars.Test/ViewEngine/ViewEngineTests.cs:line 144
```

### Other related info
This occurs in version 2.0.5 of the NuGet package and in the current (as of writing) version of the master branch.

The comment token is encountered in [version 4.0.1 of the Casper theme](https://github.com/TryGhost/Casper/blob/96aac800812e5d4b761be62a946f25ef0b1bebf5/post.hbs#L72-L76).

**Comment by heemskerkerik** [comment]
While looking into the issue, I found out that it is more narrow; it only applies to comments that _start with_ HTML.

E.g. this would be fine:
```hbs
{{!--
  This is HTML:
  <div>HTML</div>
--}}
```

But this would not:
```hbs
{{!--
  <div>HTML</div>
--}}
```
